### ISSUE TITLE
Throws "expected 0 argments, got 3" error with Flambe.

### ISSUE THREAD

**Issue by SavedByZero** [openfl/actuate#18]
Any idea why this happens?  I copied and pasted lines that work perfectly in NME/OpenFL and applied them to Flambe's ImageSprites, like so:

Actuate.tween(plane, 2, { y:100 } );

And get this error every time:  
"Argument count mismatch on motion.actuators::SimpleActuator(). Expected 0, got 3"

Of course, I'm assuming Actuate was meant for Haxe general, and not just OpenFL, but if I'm wrong, pay me no heed.

**Comment by jgranick** [comment]
I believe this was resolved, sorry for the delay on following on this issue :)
