### ISSUE TITLE
Actuate.update() crashes on Neko

### ISSUE THREAD

**Issue by jacobalbano** [openfl/actuate#22]
Using Actuate.update() causes a crash when running on the Neko target. I'm also testing with Flash and Android, and it works fine on both of those.

Replication code:

```actionscript
Actuate.update(function(t) {}, duration, [0.0], [1.0]);
```

The stacktrace on error:
```
Called from motion.Actuate::update line 387
Called from motion.Actuate::tween line 310
Called from motion.Actuate::getLibrary line 75
Uncaught exception - Invalid field access : __id__
```

**Comment by jgranick** [comment]
I've done a patch to fix this for now, it works for a standard `Actuate.update`, it won't work with `Actuate.stop`, but the standard flow works, until there's a more significant architectural change to help account for this.

Thanks again for the pull request, I did try it, but it broke other types of tweens (thus what I mean about a more significant redesign)

Sorry for the long delay, been getting some tests up and running, which made it easier to spot and resolve this

**Comment by jgranick** [comment]
Okay, got a new, better solution, based on your pull, @ofrzeta. Thanks again for your guys help :smile:
