### ISSUE TITLE
margin of error?

### ISSUE THREAD

**Issue by SavedByZero** [openfl/actuate#38]
I'm working on a project that depends on timing down to the millisecond (or pretty close), and I noticed that Actuate.tween isn't completely precise.  On the XCode simulator and my iPhone itself, if I tell it to tween for 600 milliseconds (0.6 seconds), it'll be anywhere from 632 milliseconds to (rarely) 700 milliseconds.   Is this normal behavior?  Is there a more precise way to tween?

**Comment by jgranick** [comment]
Actuate uses a hybrid approach to frame timing, on ENTER_FRAME events, it checks Lib.getTimer (), which is a timestamp provided either by SDL (which should be fairly accurate) or by a system Date function.

This means that Actuate is designed to by synchronized with rendering, and intentionally is not going to occur at the exact moment specified. If you need more exact timing, I would recommend using the haxe.Timer class, though this still may have discrepencies on certain targets
