### ISSUE TITLE
Is there a way to determine if actuate is still tweening

### ISSUE THREAD

**Issue by hoseyjoe** [openfl/actuate#46]
I added this function but I am sure there is a better way

public static function isRunning():Bool {
	var result:Bool = false;
	for (library in targetLibraries) {
		result = true;
		break;
	}
	return result;
}

**Comment by jgranick** [comment]
Not under the current architecture, but I think with some changes, it would be possible to get this in a nice way

**Comment by jgranick** [comment]
Hey again, I just added your pull request, naming it `Actuate.isActive` rather than `isRunning`, thank you :smile:
