### ISSUE TITLE
Actuate.update not working with latest OpenFL/Haxe?

### ISSUE THREAD

**Issue by isohedral** [openfl/actuate#48]
I upgraded this morning to Haxe 3.1.3 and OpenFL 2.2.1, and it seems as if Actuate.update isn't working anymore.  I tried a simple isolated test:

```
package;

import lime.app.Application;
import motion.Actuate;

class Main extends Application {
    private function blah( x : Int ) {
        trace( x );
    }
   
    public function new () {
        super ();
        Actuate.update( blah, 1, [0], [10] );
    }
}
```

And I receive a compile-time error:

```
Source/Main.hx:13: characters 2-38 : Type parameter must be a class or enum instance (found x : Int -> Void)
```

Needless to say, code like this was working fine until now.  I read this as a change in the language itself invalidating this approach, but I don't know the internals of Haxe well enough to be sure.  In any case, advice on how to fix or work around the problem would be most welcome.  Thanks.

**Comment by restorer** [comment]
For me it's like a haxe bug with @:generic compiler metadata.

without @:generic - http://try.haxe.org/#5cb59 - ok, work as expected.
with @:generic - http://try.haxe.org/#9B6c7 - compile error

**Comment by isohedral** [comment]
Yep, that got things compiling correctly.  Unfortunately, my program now crashes when it tries to invoke Actuate.update.  Here's the stack trace:

```
Called from ? line 1
Called from ApplicationMain.hx line 57
Called from ApplicationMain.hx line 18
Called from lime/app/Preloader.hx line 63
Called from lime/app/Preloader.hx line 217
Called from ApplicationMain.hx line 65
Called from Main.hx line 6
Called from a C function
Called from Main.hx line 13
Called from motion/Actuate.hx line 398
Called from motion/Actuate.hx line 331
Called from motion/Actuate.hx line 75
Uncaught exception - Invalid field access : __id__
```

Any thoughts on the cause?  Sorry that I'm not diving very deeply into the Actuate source code myself right now -- I'm not so familiar with Haxe metadata tags, and in any case I don't have enough time these days.  But let me know if you can see the cause. It might possibly related to the inability to use a function as a key in an ObjectMap?  That's what's happening around line 75 of Actuate.hx.

**Comment by jgranick** [comment]
Hey, I just hacked in support for `Actuate.update` on the Neko target, it will break support for being able to `Actuate.stop` the tween, but at least the standard case works for now, until we have a better solution :smile:

**Comment by jgranick** [comment]
Okay, got a real solution, thanks guys :smile:

**Comment by isohedral** [comment]
Looks good, thanks so much!
