### ISSUE TITLE
Stop Actuate.timer() ?

### ISSUE THREAD

**Issue by davellx** [openfl/actuate#52]
Hi,

I was trying to use the RoxGesture for one of my projects but it seems that it works with an older version of Actuate where we could use the stop() method the GenericActuator generated by the Actuate.timer() method. 
It seems that this stop() method is now private (why?) so I was wondering if there was a simple alternative for stopping Actuate.timer() ?

Thanks,

**Comment by davellx** [comment]
I managed to change the original code with a Timer.delay() and Actuate.stop(), sorry for the bother. :)

**Comment by Greg209** [comment]
I've just come across this exact same issue and agree that currently there is no way to stop a specific var t = Actuate.timer(); as t will not have access to the private stop() method. This also goes for any instanced tween e.g. var myTween = Actuate.tween(...). The returned GenericTween<T> (myTween) only allows events to be attached. There is no reference to target, stop, pause, resume, apply, move. 

Is there a reason for this? It feels quite limiting.

**Comment by davellx** [comment]
Actually the doc specifies that you can manage the tweens with the static methods : 
Actuate.stop (MySprite);
Actuate.pause (MySprite);
Actuate.pause (MySprite, MyOtherSprite);
Actuate.resume (MySprite);
Actuate.resume (MySprite, MyOtherSprite);
etc. (cf. https://github.com/openfl/actuate/blob/master/README.md#usage)

The problem is on Actuate.timer() that is not used on a object and unstoppable (like the movie with Denzel Washington and Chris Pine). But it is also totally unusefull once you know about Timer.delay(). :D

**Comment by Greg209** [comment]
Yeah the static methods are fine but like you I hit the problem with RoxGestures and have worked around it with Timer.delay - but wasted a bit of time in the process ;)

**Comment by davellx** [comment]
Argh, we did the same job !
Here's my version of RoxGesture updated for recent Actuate : 
https://github.com/davellx/roxlib

I tried to pull a request but it seems that this lib is abandoned.

**Comment by Greg209** [comment]
Ha!! Not far from being identical to mine - that'll teach me for not looking at the RoxGesture forks close enough. I like the use of .bind(pt) to pass pt to the timer function, not seen that before. Thnks

**Comment by jgranick** [comment]
Can you do this?

```haxe
var t = Actuate.timer (2);
Actuate.stop (t);
```

**Comment by Greg209** [comment]
That does indeed seem to work. Simple as that!!! Having now looked at the static stop method I now see that it checks to see if it is an IGenericActuator and then calls the private stop internally. Yet again, I probably should have looked through the code a little better first. Thanks.

**Comment by jgranick** [comment]
sorry about the lack of docs. The stop is hidden because of completion when chaining
