### ISSUE TITLE
Working only with flash

### ISSUE THREAD

**Issue by Krzycho666** [openfl/actuate#53]
I've tried to build to windows the project of mine were I use actuate in very few places. What I've found, that some animations don't really work as they should. It's same ie. on Neko.

Actuate.tween( sprite, 0.5, { x: newx } ).ease( Expo.easeInOut ).onComplete( onArrive );	Actuate.tween( sprite, 0.5, { y: newy } ).ease( Expo.easeInOut );

They dont really tween. Sprites position never change, but onComplete function goes on when it should...  What's the problem?

**Comment by jgranick** [comment]
If you can share a sample, I could try to take a look. If you use `openfl create ActuateExample` and `openfl test ActuateExample neko` it should work, and that's basically an X or a Y tween

**Comment by Krzycho666** [comment]
Hmm... Well... Actualy everything works like a charm about this example. It looks like my code works in different way on other platforms than flash. I'll figure it out somehow. Thanks than ;)

**Comment by jgranick** [comment]
If you can boil it down to a scenario (like "it's because I'm using a custom getter/setter") that's reproducible, then I'm glad to see if we can make sure it works as expected, on as many targets as possible :smile:
