### ISSUE TITLE
Deltatime update

### ISSUE THREAD

**Issue by fabiopicchi** [openfl/actuate#56]
There should be a function that updates all tweens based on a delta time parameter that you pass. This way it would be possible to synchronise Actuate's update with an implementation of a game loop.

I will look into how this can be done as soon as I can!

**Comment by fabiopicchi** [comment]
I read through the library's code and found the actuate_manual_time and actuate_manual_update compiler flags that serve exactly this purpose. Sorry for posting the issue before reading the code =/

Maybe it should be documented on the README file.

**Comment by jgranick** [comment]
It was a pull, I think there should be a more elegant API for this
