### ISSUE TITLE
onComplete is never called with "update"

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [openfl/actuate#59]
It seems, that when doing 

```
Actuate.update(...).onComplete(...);
```

The function, passed to onComplete is never called.

**Comment by jgranick** [comment]
It's working here in my test, do you have some simple sample code I could use to recreate it?

**Comment by jgranick** [comment]
However, I did just resolve an issue I found -- sometimes the last call was not made on an `Actuate.update` tween, so it would reach 0.997 (for example) instead of 1, this might be it

**Comment by RudolfVonKrugstein** [comment]
```
package;

import openfl.display.Sprite;
import motion.Actuate;

class Main extends Sprite {

  public function new () {
    super ();
    var a = Actuate.update(this.run, 1.0, [0.0,0.0],[10.0,20.0]);
    a.onComplete(function() {
      trace("-----------> done1");
    },[]);
    var a2 = Actuate.update(this.run, 1.0, [10.0,20.0],[0.0,0.0]);
    a.onComplete(function() {
      trace("----------> done2");
    },[]);

  }

  public function run(a : Float, b : Float) {
    /*trace("a: " + a);
      trace("b: " + b);*/
  }
}
```

Only done2 is printed. Maye because the same function is used twice?

**Comment by RudolfVonKrugstein** [comment]
can the problem in my last example be confirmed or is something wrong with my setup?

**Comment by jgranick** [comment]
Oh, Actuate automatically overrides existing tweens, normally this is desired (so that you do not have two tweens trying to change the same object property at the same time) but I suppose that `update` should possibly not do this. Try adding `false` as the last parameter when you call `Actuate.update` the second time

**Comment by RudolfVonKrugstein** [comment]
Good point!
But still, this code:

```
package;

import openfl.display.Sprite;
import motion.Actuate;

class Main extends Sprite {

  public function new () {
    super ();
    var a = Actuate.update(this.run, 1.0, [0.0,0.0],[10.0,20.0],false);
    a.onComplete(function() {
      trace("-----------> done1");
    },[]);
    var a2 = Actuate.update(this.run, 1.0, [10.0,20.0],[0.0,0.0],false);
    a.onComplete(function() {
      trace("----------> done2");
    },[]);
  }
  public function run(a : Float, b : Float) {
    /*trace("a: " + a);
      trace("b: " + b);*/
  }
}
```

Still only outputs:

```
Main.hx:19: ----------> done2
```
