### ISSUE TITLE
Floating point tweening values are interpreted as integers

### ISSUE THREAD

**Issue by grapefrukt** [openfl/actuate#61]
This affects Flash and Native targets for version 1.8.5. HTML5 is fine, as are older versions. Using Haxe 3.1.3.

```haxe
package;

import haxe.Timer;
import motion.Actuate;
import openfl.display.Sprite;

class Main extends Sprite {

	var floatValue:Float = WHOLE;
	
	public static inline var WHOLE:Float = 1;
	public static inline var HALF:Float = .5;
	
	public function new() {
		super();
		
		Timer.delay(down, 300);
	}
	
	function down() {
		Actuate.tween(this, .2, { floatValue : HALF } ).onComplete(output);
	}
	
	function output() {
		trace(floatValue);
	}

}
```

Expected output:

	Main.hx:36: 0.5

Actual output:

	Main.hx:36: 0

**Comment by grapefrukt** [comment]
The same issue is present on Haxe 3.2.0 as well.

**Comment by jgranick** [comment]
Would you mind seeing if the GIT version of Actuate fixes this?

**Comment by grapefrukt** [comment]
Well, that was sloppy work on my part. Turns out it does work with the current version in git!
Nevermind then!
