### ISSUE TITLE
Issue rotation

### ISSUE THREAD

**Issue by alagatar** [openfl/actuate#62]
Hi,
How tween object rotation to 0 radians?
var angle:Float=10 * Math.PI / 180;
Actuate.tween(sprite, 1, {rotation:angle}).ease(Quart.easeOut);
After some time i need rotate back to 0:
Actuate.tween(sprite, 1, {rotation:0}).ease(Quart.easeOut);//There reset immediately without smooth

**Comment by jgranick** [comment]
Did this end up not being an issue?

**Comment by alagatar** [comment]
Sorry this is my mistake, becouse of use dce it remove some fields from tilelayer.

**Comment by jgranick** [comment]
Ah, gotcha. Perhaps it would make sense to add @:keep to some of those to make it work a bit nicer :smile:

**Comment by jcward** [comment]
@jgranick - I'm hitting this issue now -- with DCE, rotations aren't being applied. But what property of what class is being removed to make this happen? I have rotation applied elsewhere in the code, so I know Sprite's rotation property exists. Any ideas?
