### ISSUE TITLE
Not compatible with -dce full ?

### ISSUE THREAD

**Issue by alamboley** [openfl/actuate#74]
I tried Actuate with a simple code `Actuate.tween(bird, 1, {alpha:0.2}).repeat().reflect();` it worked fine. I'm surprised that adding `-dce full` to the `hxml` file makes Actuate not working anymore (tested on js and flash targets)...

Using `-dce full` is really required when working with Nape and HTML5!

**Comment by jgranick** [comment]
Would you mind seeing if this helps?

https://github.com/openfl/openfl/commit/cc7c08f19bb68a908ec4da5d2438f4f6b2875b56

Thank you! :smile:

**Comment by alamboley** [comment]
Unfortunately, I'm not using OpenFL. Not sure how to add the `@:keep` using this syntax #73

**Comment by jgranick** [comment]
Oh, gotcha

Does this work?

```@:keep public var alpha(get, set):Float;```

**Comment by alamboley** [comment]
Unfortunately no :(

**Comment by jgranick** [comment]
Does it work if you use `@:keep` on each of the getter/setter methods?

**Comment by alamboley** [comment]
Adding the `@:keep` only on each getter/setter methods works fine 👍 thanks!

Any ideas concerning the other issue on the HTML5 target?

**Comment by jgranick** [comment]
Actuate tries to detect when something is a real property -- perhaps when `@:isVar` is present, this causes it to set the property directly and bypass the getter and setter. This is faster, but obviously misses behavior.

I've wanted to redesign Actuate for Haxe strong types, I need to think about how that would work :wink:

(it's the dynamics that are causing these issues)
