### ISSUE TITLE
requestAnimationFrame in js target?

### ISSUE THREAD

**Issue by jcward** [openfl/actuate#82]
Is there a reason that actuate doesn't use Javascript's [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)? Browser support looks [pretty good](http://caniuse.com/#feat=requestanimationframe).

I tried injecting it [here](https://github.com/openfl/actuate/blob/master/motion/actuators/SimpleActuator.hx#L84), quick'n'dirty with:

```
        #elseif js
          var cycle:Float->Void = null;
          cycle = function(t) {
            stage_onEnterFrame();
            js.Browser.window.requestAnimationFrame(cycle);
          }
          cycle(0);
        #else
```

And the tweens are visibly smoother than the 33ms `Timer` in the else-clause - and perhaps obviously so, that's what `requestAnimationFrame` is for.

So is there some reason I'm overlooking that it's not used in js?

**Comment by jgranick** [comment]
Closed via #81 :smile:

**Comment by jcward** [comment]
Wow, crazy timing.

**Comment by jgranick** [comment]
"I anticipated your request!"

![image](https://user-images.githubusercontent.com/833997/27357177-09532a92-55c6-11e7-97a5-3e3d53738b2d.png)

**Comment by jgranick** [comment]
BTW, sorry if the reference is too obscure :smile:

https://www.youtube.com/watch?v=le2eB2xtvBQ
